name: Build and Release

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.2.3)"
        required: true
      description:
        description: "Description"
        required: false
        default: ""

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-name: dist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Determine Emscripten version
        id: emscripten
        run: echo "VERSION=$(./build.py --emcc-version)" >> "$GITHUB_OUTPUT"

      - name: Setup emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ steps.emscripten.outputs.VERSION }}

      - name: Show emcc version
        run: emcc --version

      - name: Build stockfishes
        run: ./build.py dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: |
            *.js
            *.wasm

  release:
    name: Release
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Validate version
        run: |
          [[ "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]] || \
          (echo "Version must start with 'v' and match 'v<major>.<minor>.<patch>'" && exit 1)

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist

      - name: Setup Node (for npm publish)
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org/

      - name: Bump package.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          NPM_VERSION="${GITHUB_VERSION#v}"
          npm version "$NPM_VERSION" --allow-same-version
        env:
          GITHUB_VERSION: ${{ github.event.inputs.version }}

      - name: Publish to npm
        run: |
          npm publish --provenance --access public
          git push origin HEAD --follow-tags

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
